### ISSUE TITLE
Compile error in web

### ISSUE THREAD

**Issue by KaushickSArgekar** [neumorphic/neumorphic.flutter#14] opened 2020-07-08 15:48 UTC
Unhandled exception:

InvalidType doesn't have nullability.
#0      InvalidType.nullability  (package:kernel/ast.dart:6750:34)

**Comment by predatorx7** [comment] 2020-07-15 11:33
Could you give more information about this problem?

Follow the below template:

### Description



### Steps to Reproduce

1. First Step
2. Second Step
3. and so on…

**Expected behavior:**

What you expect to happen

**Actual behavior:**

What actually happens

**Reproduces how often:**

What percentage of the time does it reproduce?

### Version

The version of neumorphic.flutter you're using

### Additional Information

Paste the output of `flutter doctor -v`

Additional information about the issue

**Comment by Nashua354** [comment] 2020-07-27 20:45
Having the same issue.
Description.
I just added the package and did flutter pub get. It worked fine.
then did flutter run -d chrome. Got the error while compiling the project.

The project runs fine without the package.
 This is the error :
`Unhandled exception:                                            
InvalidType doesn't have nullability.                                                                              
#0      InvalidType.nullability (package:kernel/ast.dart:6750:34)                                                  
#1      _CacheTable._typeString (package:dev_compiler/src/kernel/type_table.dart:71:28)`

I'm using neumorphic; 0.3.2
This is my flutter doctor:
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
[✓] Connected device (2 available)

I don't need to build on a ios system, so no need for it.

**Comment by predatorx7** [comment] 2020-07-28 02:21
I could not reproduce your error.
However, in my build, I found that there were breaking changes caused by `$FLUTTER_HOME/packages/flutter/lib/src/widgets/text_selection.dart:136:10` in flutter beta channel.
Removing neumorphic text selection allowed a successful web build possible.

**Comment by Ferdzzzzzzzz** [comment] 2020-07-29 15:45
@predatorx7 do you have any ETA for stability on beta? Or will I have to wait for web to merge into stable? 😄

**Comment by predatorx7** [comment] 2020-07-29 15:56
Yes, I'm working on a beta.

**Closed** 2020-08-09 01:20 UTC
Labels: bug

**Comment by SergeShkurko** [comment] 2020-08-09 01:31
Published in [0.4.0](https://pub.dev/packages/neumorphic/versions/0.4.0)
